------------------------------------------------------
-- E% 의류 ESG 플랫폼 전체 스키마 (Oracle)
-- 테이블 + 시퀀스 + 트리거 + 프로시저 + 스케줄러
-- 수정사항: 이메일 인증, 신고 시스템, 탈퇴 유예(30일)
-- 수정사항: 테이블 생성 순서 최적화 (FK 참조 에러 방지)
------------------------------------------------------

-- 기존 테이블 삭제 (필요시 주석 해제하여 사용)
/*
DROP TABLE REPORT_ACTIONS CASCADE CONSTRAINTS;
DROP TABLE USER_REPORTS CASCADE CONSTRAINTS;
DROP TABLE USER_TODO_CHECKS CASCADE CONSTRAINTS;
DROP TABLE ECO_TODO_TASKS CASCADE CONSTRAINTS;
DROP TABLE CHAT_MESSAGES CASCADE CONSTRAINTS;
DROP TABLE CHAT_ROOM_MEMBERS CASCADE CONSTRAINTS;
DROP TABLE CHAT_ROOMS CASCADE CONSTRAINTS;
DROP TABLE PROFILE_IMAGE_HISTORY CASCADE CONSTRAINTS;
DROP TABLE POSTS CASCADE CONSTRAINTS;
DROP TABLE RECYCLING_CENTERS CASCADE CONSTRAINTS;
DROP TABLE PICKUP_REQUESTS CASCADE CONSTRAINTS;
DROP TABLE USER_ENERGY_STATS_DAILY CASCADE CONSTRAINTS;
DROP TABLE OUTFIT_ITEMS CASCADE CONSTRAINTS;
DROP TABLE OUTFITS CASCADE CONSTRAINTS;
DROP TABLE CLASSIFICATION_REQUESTS CASCADE CONSTRAINTS;
DROP TABLE CLOTHING_FAVORITES CASCADE CONSTRAINTS;
DROP TABLE CLOTHING_IMAGES CASCADE CONSTRAINTS;
DROP TABLE CLOTHING_ITEMS CASCADE CONSTRAINTS;
DROP TABLE USER_BADGES CASCADE CONSTRAINTS;
DROP TABLE BADGES CASCADE CONSTRAINTS;
DROP TABLE ECO_POINT_TRANSACTIONS CASCADE CONSTRAINTS;
DROP TABLE EMAIL_VERIFICATION_TOKENS CASCADE CONSTRAINTS;
DROP TABLE OAUTH_ACCOUNTS CASCADE CONSTRAINTS;
DROP TABLE USER_PROFILES CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

DROP SEQUENCE S_USERS;
DROP SEQUENCE S_OAUTH_ACCOUNTS;
DROP SEQUENCE S_EMAIL_VERIFICATION_TOKENS;
DROP SEQUENCE S_ECO_POINT_TRANSACTIONS;
DROP SEQUENCE S_BADGES;
DROP SEQUENCE S_USER_BADGES;
DROP SEQUENCE S_CLOTHING_ITEMS;
DROP SEQUENCE S_CLOTHING_IMAGES;
DROP SEQUENCE S_CLOTHING_FAVORITES;
DROP SEQUENCE S_CLASSIFICATION_REQUESTS;
DROP SEQUENCE S_OUTFITS;
DROP SEQUENCE S_OUTFIT_ITEMS;
DROP SEQUENCE S_USER_ENERGY_STATS_DAILY;
DROP SEQUENCE S_PICKUP_REQUESTS;
DROP SEQUENCE S_RECYCLING_CENTERS;
DROP SEQUENCE S_POSTS;
DROP SEQUENCE S_PROFILE_IMAGE_HISTORY;
DROP SEQUENCE S_CHAT_ROOMS;
DROP SEQUENCE S_CHAT_ROOM_MEMBERS;
DROP SEQUENCE S_CHAT_MESSAGES;
DROP SEQUENCE S_ECO_TODO_TASKS;
DROP SEQUENCE S_USER_TODO_CHECKS;
DROP SEQUENCE S_USER_REPORTS;
DROP SEQUENCE S_REPORT_ACTIONS;
*/

-- [초기화] 기존 테이블/시퀀스 삭제 (필요시 실행)
/*
BEGIN
  FOR c IN (SELECT table_name FROM user_tables) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || c.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
  FOR s IN (SELECT sequence_name FROM user_sequences) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
END;
/
*/

------------------------------------------------------
-- 1. USERS (회원 기본정보)
------------------------------------------------------
CREATE TABLE USERS (
  ID          NUMBER(19)    PRIMARY KEY,
  LOGIN_ID    VARCHAR2(50)  NOT NULL,
  PASSWORD    VARCHAR2(255) NOT NULL,
  NAME        VARCHAR2(100) NOT NULL,
  PHONE       VARCHAR2(20),
  EMAIL       VARCHAR2(255),
  ADDRESS     VARCHAR2(255),
  ADDRESS_DETAIL VARCHAR2(200), 
  BIRTH_DATE  DATE,
  ROLE        VARCHAR2(20)  DEFAULT 'USER',
  STATUS      VARCHAR2(20)  DEFAULT 'ACTIVE',
  MEM_IMG     VARCHAR2(255),
  EMAIL_VERIF_STATUS VARCHAR2(20) DEFAULT 'NONE', 
  WITHDRAWAL_AT TIMESTAMP,
  CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT  TIMESTAMP,
  CONSTRAINT UQ_USERS_LOGIN_ID UNIQUE (LOGIN_ID),
  CONSTRAINT UQ_USERS_EMAIL    UNIQUE (EMAIL)
);

CREATE SEQUENCE S_USERS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_USERS_ID
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_USERS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 1-1. USER_PROFILES
------------------------------------------------------
CREATE TABLE USER_PROFILES (
  USER_ID               NUMBER(19)   PRIMARY KEY,
  NICKNAME              VARCHAR2(50),
  AVATAR_URL            VARCHAR2(500),
  TOTAL_WATER_SAVED_L   NUMBER(12,2) DEFAULT 0,
  TOTAL_CARBON_SAVED_KG NUMBER(12,2) DEFAULT 0,
  ECO_POINTS            NUMBER(10)   DEFAULT 0,
  TOTAL_COLLECTED_KG    NUMBER(12,2) DEFAULT 0,
  TOTAL_CLOTHING_COUNT  NUMBER(10)   DEFAULT 0,
  LAST_LOGIN_AT         TIMESTAMP,
  GENDER                VARCHAR2(10),
  STYLE_PREFERENCE      VARCHAR2(100),
  CONSTRAINT FK_USER_PROFILES_USERS
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

------------------------------------------------------
-- 1-2. OAUTH_ACCOUNTS
------------------------------------------------------
CREATE TABLE OAUTH_ACCOUNTS (
  ID               NUMBER(19)   PRIMARY KEY,
  USER_ID          NUMBER(19)   NOT NULL,
  PROVIDER         VARCHAR2(50) NOT NULL,
  PROVIDER_USER_ID VARCHAR2(255) NOT NULL,
  LINKED_AT        TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_OAUTH_PROVIDER_USER UNIQUE (PROVIDER, PROVIDER_USER_ID),
  CONSTRAINT FK_OAUTH_USERS
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE S_OAUTH_ACCOUNTS START WITH 1 INCREMENT BY 1; 

CREATE OR REPLACE TRIGGER TRG_OAUTH_ACCOUNTS_ID              
BEFORE INSERT ON OAUTH_ACCOUNTS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_OAUTH_ACCOUNTS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 1-3. EMAIL_VERIFICATION_TOKENS
------------------------------------------------------
CREATE TABLE EMAIL_VERIFICATION_TOKENS (
  ID         NUMBER(19)   PRIMARY KEY,
  USER_ID    NUMBER(19)   NOT NULL,
  TOKEN      VARCHAR2(255) NOT NULL,
  EXPIRES_AT TIMESTAMP    NOT NULL,
  USED_AT    TIMESTAMP,
  CREATED_AT TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_EMAIL_TOKEN UNIQUE (TOKEN),
  CONSTRAINT FK_EMAIL_TOKENS_USERS
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE S_EMAIL_VERIFICATION_TOKENS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_EMAIL_VERIFICATION_TOKENS_ID    
BEFORE INSERT ON EMAIL_VERIFICATION_TOKENS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_EMAIL_VERIFICATION_TOKENS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 1-4. ECO_POINT_TRANSACTIONS
------------------------------------------------------
CREATE TABLE ECO_POINT_TRANSACTIONS (
  ID          NUMBER(19)   PRIMARY KEY,
  USER_ID     NUMBER(19)   NOT NULL,
  POINTS      NUMBER(10)   NOT NULL,
  REASON_TYPE VARCHAR2(50) NOT NULL,
  DESCRIPTION VARCHAR2(255),
  CREATED_AT  TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_ECO_POINTS_USERS
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE S_ECO_POINT_TRANSACTIONS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_ECO_POINT_TRANSACTIONS_ID       
BEFORE INSERT ON ECO_POINT_TRANSACTIONS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_ECO_POINT_TRANSACTIONS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 2. BADGES & USER_BADGES
------------------------------------------------------
CREATE TABLE BADGES (
  ID              NUMBER(19)   PRIMARY KEY,
  CODE            VARCHAR2(50) NOT NULL,
  NAME            VARCHAR2(100) NOT NULL,
  DESCRIPTION     VARCHAR2(255),
  ICON_URL        VARCHAR2(500),
  CONDITION_TYPE  VARCHAR2(50),
  THRESHOLD_VALUE NUMBER(12,2),
  CREATED_AT      TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_BADGES_CODE UNIQUE (CODE)
);

CREATE SEQUENCE S_BADGES START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_BADGES_ID                        
BEFORE INSERT ON BADGES
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_BADGES.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

CREATE TABLE USER_BADGES (
  ID         NUMBER(19)   PRIMARY KEY,
  USER_ID    NUMBER(19)   NOT NULL,
  BADGE_ID   NUMBER(19)   NOT NULL,
  AWARDED_AT TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_USER_BADGE UNIQUE (USER_ID, BADGE_ID),
  CONSTRAINT FK_USER_BADGES_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_USER_BADGES_BADGES FOREIGN KEY (BADGE_ID) REFERENCES BADGES(ID)
);

CREATE SEQUENCE S_USER_BADGES START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_USER_BADGES_ID                    
BEFORE INSERT ON USER_BADGES
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_USER_BADGES.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- [위치변경] 3. COMMON_CODES (공통 코드 / 소재 마스터)
-- ※ 주의: CLOTHING_MATERIALS보다 먼저 생성되어야 함
------------------------------------------------------
CREATE TABLE COMMON_CODES (
  CODE_ID       VARCHAR2(20) PRIMARY KEY,
  GRP_CODE      VARCHAR2(20) NOT NULL,
  CODE_NAME     VARCHAR2(100) NOT NULL,
  CARBON_FACTOR NUMBER(10, 4) DEFAULT 0,
  IS_USE        CHAR(1)       DEFAULT 'Y'
);

INSERT INTO COMMON_CODES VALUES ('MAT_001', 'MATERIAL', '면(Cotton)', 4.0, 'Y');
INSERT INTO COMMON_CODES VALUES ('MAT_002', 'MATERIAL', '폴리에스터', 9.2, 'Y');
INSERT INTO COMMON_CODES VALUES ('MAT_003', 'MATERIAL', '나일론', 9.5, 'Y');
INSERT INTO COMMON_CODES VALUES ('MAT_004', 'MATERIAL', '울(Wool)', 12.0, 'Y');
INSERT INTO COMMON_CODES VALUES ('MAT_UNKNOWN', 'MATERIAL', '알 수 없음', 5.0, 'Y');
INSERT INTO COMMON_CODES VALUES ('PART_OUT', 'PART_TYPE', '겉감', 0, 'Y');
INSERT INTO COMMON_CODES VALUES ('PART_LIN', 'PART_TYPE', '안감', 0, 'Y');
INSERT INTO COMMON_CODES VALUES ('PART_FIL', 'PART_TYPE', '충전재', 0, 'Y');

------------------------------------------------------
-- 4. CLOTHING_ITEMS (내 옷장)
------------------------------------------------------
CREATE TABLE CLOTHING_ITEMS (
  ID               NUMBER(19)   PRIMARY KEY,
  USER_ID          NUMBER(19)   NOT NULL,
  NAME             VARCHAR2(255),
  CATEGORY         VARCHAR2(50),
  BRAND            VARCHAR2(100),
  ITEM_SIZE        VARCHAR2(20),
  COLOR            VARCHAR2(50),
  PREFERENCE       NUMBER(10),
  DETAIL_DESC      VARCHAR2(1000),
  WEIGHT_G 		   NUMBER(10,2),
  IS_WEIGHT_EST    CHAR(1) DEFAULT 'N',
  CONDITION_GRADE  VARCHAR2(100),
  STATUS           VARCHAR2(20) DEFAULT 'IN_CLOSET',
  SEASON           VARCHAR2(20),
  LIFECYCLE_TYPE   VARCHAR2(20),
  LIFECYCLE_DETAIL VARCHAR2(20),
  IS_FOR_SALE      CHAR(1)      DEFAULT 'N',
  ACQUIRED_AT      DATE,
  DISPOSED_AT      DATE,
  DISPOSAL_METHOD  VARCHAR2(20),
  PURCHASE_PRICE   NUMBER(10,2),
  TARGET_PRICE     NUMBER(10,2),
  CREATED_AT       TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT       TIMESTAMP,
  CONSTRAINT FK_CLOTHING_ITEMS_USERS
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE S_CLOTHING_ITEMS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CLOTHING_ITEMS_ID                 
BEFORE INSERT ON CLOTHING_ITEMS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_CLOTHING_ITEMS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

CREATE TABLE CLOTHING_IMAGES (
  ID               NUMBER(19)   PRIMARY KEY,
  CLOTHING_ITEM_ID NUMBER(19)   NOT NULL,
  IMAGE_URL        VARCHAR2(500) NOT NULL,
  IS_MAIN          CHAR(1)      DEFAULT 'N',
  CREATED_AT       TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_CLOTHING_IMAGES_ITEMS
    FOREIGN KEY (CLOTHING_ITEM_ID) REFERENCES CLOTHING_ITEMS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE S_CLOTHING_IMAGES START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CLOTHING_IMAGES_ID                 
BEFORE INSERT ON CLOTHING_IMAGES
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_CLOTHING_IMAGES.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

CREATE TABLE CLOTHING_FAVORITES (
  ID               NUMBER(19)   PRIMARY KEY,
  USER_ID          NUMBER(19)   NOT NULL,
  CLOTHING_ITEM_ID NUMBER(19)   NOT NULL,
  CREATED_AT       TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_FAVORITE_UNIQUE UNIQUE (USER_ID, CLOTHING_ITEM_ID),
  CONSTRAINT FK_FAVORITES_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_FAVORITES_ITEMS FOREIGN KEY (CLOTHING_ITEM_ID) REFERENCES CLOTHING_ITEMS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE S_CLOTHING_FAVORITES START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CLOTHING_FAVORITES_ID              
BEFORE INSERT ON CLOTHING_FAVORITES
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_CLOTHING_FAVORITES.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 4-1. CLOTHING_MATERIALS (의류-소재 매핑)
------------------------------------------------------
CREATE TABLE CLOTHING_MATERIALS (
  ID               NUMBER(19)   PRIMARY KEY,
  CLOTHING_ITEM_ID NUMBER(19)   NOT NULL,
  PART_CODE        VARCHAR2(20) NOT NULL,
  MATERIAL_CODE    VARCHAR2(20) NOT NULL,
  PERCENTAGE       NUMBER(5,2)  NOT NULL,

  CONSTRAINT FK_MAT_ITEM FOREIGN KEY (CLOTHING_ITEM_ID) REFERENCES CLOTHING_ITEMS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_MAT_CODE_PART FOREIGN KEY (PART_CODE) REFERENCES COMMON_CODES(CODE_ID),
  CONSTRAINT FK_MAT_CODE_MAT FOREIGN KEY (MATERIAL_CODE) REFERENCES COMMON_CODES(CODE_ID),
  CONSTRAINT UQ_CLOTHING_MAT UNIQUE (CLOTHING_ITEM_ID, PART_CODE, MATERIAL_CODE)
);

CREATE SEQUENCE S_CLOTHING_MATERIALS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CLOTHING_MATERIALS_ID
BEFORE INSERT ON CLOTHING_MATERIALS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_CLOTHING_MATERIALS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 5. CLASSIFICATION_REQUESTS (AI 분석 요청)
------------------------------------------------------
CREATE TABLE CLASSIFICATION_REQUESTS (
  ID                    NUMBER(19)   PRIMARY KEY,
  USER_ID               NUMBER(19)   NOT NULL,
  CLOTHING_ITEM_ID      NUMBER(19),
  IMAGE_URL             VARCHAR2(500) NOT NULL,
  LABEL_IMAGE_URL       VARCHAR2(500),
  OCR_TEXT              CLOB,
  STATUS                VARCHAR2(20)  DEFAULT 'PENDING',
  PREDICTED_GRADE       VARCHAR2(20),
  PREDICTED_MATERIAL    VARCHAR2(50),
  PREDICTED_CATEGORY    VARCHAR2(50),
  CLASSIFICATION_TYPE   VARCHAR2(20),
  CLASSIFICATION_DETAIL VARCHAR2(20),
  IS_USER_CORRECTED     CHAR(1)       DEFAULT 'N',
  PROCESSED_AT          TIMESTAMP,
  CREATED_AT            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_CLASS_REQ_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_CLASS_REQ_ITEMS FOREIGN KEY (CLOTHING_ITEM_ID) REFERENCES CLOTHING_ITEMS(ID) ON DELETE SET NULL
);

CREATE SEQUENCE S_CLASSIFICATION_REQUESTS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CLASSIFICATION_REQUESTS_ID         
BEFORE INSERT ON CLASSIFICATION_REQUESTS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_CLASSIFICATION_REQUESTS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 6. OUTFITS / OUTFIT_ITEMS (코디)
------------------------------------------------------
CREATE TABLE OUTFITS (
  ID              NUMBER(19)   PRIMARY KEY,
  USER_ID         NUMBER(19)   NOT NULL,
  TITLE           VARCHAR2(255),
  DESCRIPTION     VARCHAR2(500),
  SOURCE          VARCHAR2(20)  DEFAULT 'AI',
  CONTEXT_TAG     VARCHAR2(50),
  CONTEXT_WEATHER VARCHAR2(50),
  IS_OOTD         CHAR(1)       DEFAULT 'N',
  VISIBILITY      VARCHAR2(20)  DEFAULT 'PRIVATE',
  MAIN_IMAGE_URL  VARCHAR2(500),
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_OUTFITS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE S_OUTFITS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_OUTFITS_ID                            
BEFORE INSERT ON OUTFITS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_OUTFITS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

CREATE TABLE OUTFIT_ITEMS (
  ID               NUMBER(19)   PRIMARY KEY,
  OUTFIT_ID        NUMBER(19)   NOT NULL,
  CLOTHING_ITEM_ID NUMBER(19)   NOT NULL,
  ROLE             VARCHAR2(20),
  CREATED_AT       TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_OUTFIT_ITEMS_OUTFITS FOREIGN KEY (OUTFIT_ID) REFERENCES OUTFITS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_OUTFIT_ITEMS_ITEMS FOREIGN KEY (CLOTHING_ITEM_ID) REFERENCES CLOTHING_ITEMS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE S_OUTFIT_ITEMS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_OUTFIT_ITEMS_ID                       
BEFORE INSERT ON OUTFIT_ITEMS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_OUTFIT_ITEMS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 7. USER_ENERGY_STATS_DAILY
------------------------------------------------------
CREATE TABLE USER_ENERGY_STATS_DAILY (
  ID            NUMBER(19)   PRIMARY KEY,
  USER_ID       NUMBER(19)   NOT NULL,
  STAT_DATE     DATE         NOT NULL,
  RECYCLED_KG   NUMBER(10,2) DEFAULT 0,
  WATER_SAVED_L NUMBER(12,2) DEFAULT 0,
  CO2_SAVED_KG  NUMBER(12,2) DEFAULT 0,
  ITEMS_COUNT   NUMBER(10)   DEFAULT 0,
  CREATED_AT    TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_ENERGY_STATS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT UQ_ENERGY_STATS_USER_DATE UNIQUE (USER_ID, STAT_DATE)
);

CREATE SEQUENCE S_USER_ENERGY_STATS_DAILY START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_USER_ENERGY_STATS_DAILY_ID           
BEFORE INSERT ON USER_ENERGY_STATS_DAILY
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_USER_ENERGY_STATS_DAILY.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 8. PICKUP_REQUESTS
------------------------------------------------------
CREATE TABLE PICKUP_REQUESTS (
  ID               NUMBER(19)   PRIMARY KEY,
  USER_ID          NUMBER(19)   NOT NULL,
  CLOTHING_ITEM_ID NUMBER(19),
  REQUEST_TYPE     VARCHAR2(20) NOT NULL,
  STATUS           VARCHAR2(20) DEFAULT 'REQUESTED',
  PICKUP_ADDRESS   VARCHAR2(500),
  DESIRED_DATE     DATE,
  MEMO             VARCHAR2(500),
  CREATED_AT       TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT       TIMESTAMP,
  CONSTRAINT FK_PICKUP_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PICKUP_ITEMS FOREIGN KEY (CLOTHING_ITEM_ID) REFERENCES CLOTHING_ITEMS(ID) ON DELETE SET NULL
);

CREATE SEQUENCE S_PICKUP_REQUESTS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_PICKUP_REQUESTS_ID                    
BEFORE INSERT ON PICKUP_REQUESTS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_PICKUP_REQUESTS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 9. RECYCLING_CENTERS
------------------------------------------------------
CREATE TABLE RECYCLING_CENTERS (
  ID           NUMBER(19)   PRIMARY KEY,
  NAME         VARCHAR2(255) NOT NULL,
  TYPE         VARCHAR2(20)  NOT NULL,
  ADDRESS      VARCHAR2(500),
  LAT          NUMBER(10,7),
  LON          NUMBER(10,7),
  OPEN_HOURS   VARCHAR2(255),
  PHONE        VARCHAR2(50),
  HOMEPAGE_URL VARCHAR2(500),
  CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE SEQUENCE S_RECYCLING_CENTERS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_RECYCLING_CENTERS_ID                    
BEFORE INSERT ON RECYCLING_CENTERS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_RECYCLING_CENTERS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 10. POSTS
------------------------------------------------------
CREATE TABLE POSTS (
  ID           NUMBER(19)   PRIMARY KEY,
  USER_ID      NUMBER(19)   NOT NULL,
  CATEGORY     VARCHAR2(50) NOT NULL,
  TITLE        VARCHAR2(255) NOT NULL,
  CONTENT      CLOB         NOT NULL,
  VIEW_COUNT   NUMBER(10)   DEFAULT 0,
  IS_SECRET    CHAR(1)      DEFAULT 'N',
  PARENT_POST_ID NUMBER(19),
  IS_DELETED   CHAR(1)      DEFAULT 'N',
  CREATED_AT   TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT   TIMESTAMP,
  ANSWER       CLOB,
  ANSWERED_AT  TIMESTAMP,
  CONSTRAINT FK_POSTS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_POSTS_PARENT FOREIGN KEY (PARENT_POST_ID) REFERENCES POSTS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE S_POSTS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_POSTS_ID                                    
BEFORE INSERT ON POSTS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_POSTS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 11. PROFILE_IMAGE_HISTORY
------------------------------------------------------
CREATE TABLE PROFILE_IMAGE_HISTORY (
  HIST_ID    NUMBER(19)   PRIMARY KEY,
  USER_ID    NUMBER(19)   NOT NULL,
  IMAGE_PATH VARCHAR2(255) NOT NULL,
  UPLOADED_AT DATE        DEFAULT SYSDATE NOT NULL,
  CONSTRAINT FK_PROFILE_IMAGE_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE S_PROFILE_IMAGE_HISTORY START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_PROFILE_IMAGE_HISTORY_ID                  
BEFORE INSERT ON PROFILE_IMAGE_HISTORY
FOR EACH ROW
BEGIN
  IF :NEW.HIST_ID IS NULL THEN
    SELECT S_PROFILE_IMAGE_HISTORY.NEXTVAL INTO :NEW.HIST_ID FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE PROCEDURE ADD_PROFILE_IMAGE(
  P_USER_ID    IN NUMBER,
  P_IMAGE_PATH IN VARCHAR2
)
AS
BEGIN
  INSERT INTO PROFILE_IMAGE_HISTORY(USER_ID, IMAGE_PATH) VALUES (P_USER_ID, P_IMAGE_PATH);
  UPDATE USERS SET MEM_IMG   = P_IMAGE_PATH, UPDATED_AT = SYSDATE WHERE ID = P_USER_ID;
  DELETE FROM PROFILE_IMAGE_HISTORY
  WHERE HIST_ID IN (
    SELECT HIST_ID FROM (
      SELECT HIST_ID, ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY UPLOADED_AT DESC) RN
      FROM PROFILE_IMAGE_HISTORY WHERE USER_ID = P_USER_ID
    ) WHERE RN > 5
  );
  COMMIT;
END;
/

------------------------------------------------------
-- 12. CHAT
------------------------------------------------------
CREATE TABLE CHAT_ROOMS (
  ID         NUMBER(19)   PRIMARY KEY,
  ROOM_TYPE  VARCHAR2(20),
  TITLE      VARCHAR2(255),
  ITEM_ID NUMBER(19),
  CREATED_BY NUMBER(19)   NOT NULL,
  CREATED_AT TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  CONSTRAINT FK_CHAT_ROOMS_USERS FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE S_CHAT_ROOMS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CHAT_ROOMS_ID                               
BEFORE INSERT ON CHAT_ROOMS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_CHAT_ROOMS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

CREATE TABLE CHAT_ROOM_MEMBERS (
  ID        NUMBER(19)   PRIMARY KEY,
  ROOM_ID   NUMBER(19)   NOT NULL,
  USER_ID   NUMBER(19)   NOT NULL,
  JOINED_AT TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  LEFT_AT   TIMESTAMP,
  LAST_READ_AT TIMESTAMP,
  CONSTRAINT FK_CHAT_MEMBERS_ROOM FOREIGN KEY (ROOM_ID) REFERENCES CHAT_ROOMS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_CHAT_MEMBERS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT UQ_CHAT_MEMBER UNIQUE (ROOM_ID, USER_ID)
);

CREATE SEQUENCE S_CHAT_ROOM_MEMBERS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CHAT_ROOM_MEMBERS_ID                         
BEFORE INSERT ON CHAT_ROOM_MEMBERS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_CHAT_ROOM_MEMBERS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

CREATE TABLE CHAT_MESSAGES (
  ID           NUMBER(19)   PRIMARY KEY,
  ROOM_ID      NUMBER(19)   NOT NULL,
  SENDER_ID    NUMBER(19)   NOT NULL,
  MESSAGE_TYPE VARCHAR2(20) DEFAULT 'TEXT',
  CONTENT      CLOB,
  CONTENT_ENCRYPTED BLOB,
  IMAGE_URL    VARCHAR2(500),
  OUTFIT_ID    NUMBER(19),
  CREATED_AT   TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_CHAT_MESSAGES_ROOM FOREIGN KEY (ROOM_ID) REFERENCES CHAT_ROOMS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_CHAT_MESSAGES_SENDER FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_CHAT_MESSAGES_OUTFIT FOREIGN KEY (OUTFIT_ID) REFERENCES OUTFITS(ID) ON DELETE SET NULL
);

CREATE SEQUENCE S_CHAT_MESSAGES START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CHAT_MESSAGES_ID                               
BEFORE INSERT ON CHAT_MESSAGES
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_CHAT_MESSAGES.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 13. ECO_TODO_TASKS / USER_TODO_CHECKS
------------------------------------------------------
CREATE TABLE ECO_TODO_TASKS (
  ID             NUMBER(19)   PRIMARY KEY,
  CODE           VARCHAR2(50)  NOT NULL,
  TITLE          VARCHAR2(255) NOT NULL,
  DESCRIPTION    VARCHAR2(500),
  DEFAULT_POINTS NUMBER(10)   DEFAULT 0,
  IS_ACTIVE      CHAR(1)      DEFAULT 'Y',
  SORT_ORDER     NUMBER(5),
  CREATED_AT     TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_ECO_TODO_CODE UNIQUE (CODE)
);

CREATE SEQUENCE S_ECO_TODO_TASKS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_ECO_TODO_TASKS_ID                             
BEFORE INSERT ON ECO_TODO_TASKS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_ECO_TODO_TASKS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

CREATE TABLE USER_TODO_CHECKS (
  ID            NUMBER(19)   PRIMARY KEY,
  USER_ID       NUMBER(19)   NOT NULL,
  TASK_ID       NUMBER(19)   NOT NULL,
  CHECK_DATE    DATE         NOT NULL,
  CHECKED       CHAR(1)      DEFAULT 'N',
  POINTS_EARNED NUMBER(10)   DEFAULT 0,
  CREATED_AT    TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_USER_TODO_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_USER_TODO_TASK FOREIGN KEY (TASK_ID) REFERENCES ECO_TODO_TASKS(ID),
  CONSTRAINT UQ_USER_TODO UNIQUE (USER_ID, TASK_ID, CHECK_DATE)
);

CREATE SEQUENCE S_USER_TODO_CHECKS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_USER_TODO_CHECKS_ID                             
BEFORE INSERT ON USER_TODO_CHECKS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_USER_TODO_CHECKS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 14. USER_REPORTS
------------------------------------------------------
CREATE TABLE USER_REPORTS (
  ID               NUMBER(19)   PRIMARY KEY,
  REPORTER_ID      NUMBER(19)   NOT NULL,
  REPORTED_USER_ID NUMBER(19)   NOT NULL,
  REASON_CATEGORY  VARCHAR2(50) NOT NULL,
  IS_PROCESSED     CHAR(1)      DEFAULT 'N',
  DESCRIPTION      VARCHAR2(1000),
  CREATED_AT       TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_REPORT_REPORTER FOREIGN KEY (REPORTER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_REPORT_TARGET FOREIGN KEY (REPORTED_USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE S_USER_REPORTS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_USER_REPORTS_ID
BEFORE INSERT ON USER_REPORTS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_USER_REPORTS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 16. OOTD_CALENDAR (나만의 코디 캘린더)
------------------------------------------------------
CREATE TABLE OOTD_CALENDAR (
  ID             NUMBER(19)   PRIMARY KEY,
  USER_ID        NUMBER(19)   NOT NULL,
  EVENT_DATE     DATE         NOT NULL,
  TITLE          VARCHAR2(255),
  IMAGE_BASE64   CLOB,        -- 이미지를 Base64 문자열로 직접 저장
  CREATED_AT     TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_OOTD_CAL_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE S_OOTD_CALENDAR START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_OOTD_CALENDAR_ID
BEFORE INSERT ON OOTD_CALENDAR
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_OOTD_CALENDAR.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
CREATE TABLE REPORT_ACTIONS (
  ID               NUMBER(19)   PRIMARY KEY,
  REPORT_ID        NUMBER(19),
  ADMIN_ID         NUMBER(19)   NOT NULL,
  TARGET_USER_ID   NUMBER(19)   NOT NULL,
  ACTION_TYPE      VARCHAR2(50) NOT NULL,
  ACTION_REASON    VARCHAR2(500),
  CREATED_AT       TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_ACTION_REPORT FOREIGN KEY (REPORT_ID) REFERENCES USER_REPORTS(ID) ON DELETE SET NULL,
  CONSTRAINT FK_ACTION_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_ACTION_TARGET FOREIGN KEY (TARGET_USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE S_REPORT_ACTIONS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_REPORT_ACTIONS_ID
BEFORE INSERT ON REPORT_ACTIONS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT S_REPORT_ACTIONS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------
-- 16. 탈퇴 30일 유예 자동 삭제 스케줄러
------------------------------------------------------
CREATE OR REPLACE PROCEDURE PURGE_WITHDRAWN_USERS
AS
BEGIN
  DELETE FROM USERS
  WHERE WITHDRAWAL_AT IS NOT NULL
    AND WITHDRAWAL_AT < SYSTIMESTAMP - 30;
  COMMIT;
END;
/

BEGIN
  DBMS_SCHEDULER.create_job (
    job_name        => 'JOB_PURGE_WITHDRAWN_USERS',
    job_type        => 'STORED_PROCEDURE',
    job_action      => 'PURGE_WITHDRAWN_USERS',
    start_date      => SYSTIMESTAMP,
    repeat_interval => 'FREQ=DAILY; BYHOUR=4; BYMINUTE=0; BYSECOND=0',
    enabled         => TRUE,
    comments        => '30일 지난 탈퇴 회원 영구 삭제'
  );
END;
/

-- OOTD 테이블 생성 스크립트
-- Oracle Database

-- 시퀀스 생성
CREATE SEQUENCE OOTD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE OOTD_COMMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- OOTD_POSTS 테이블
CREATE TABLE OOTD_POSTS (
    OOTD_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    IMAGE_URL VARCHAR2(500),
    TOP_CLOTHES_ID VARCHAR2(50),
    BOTTOM_CLOTHES_ID VARCHAR2(50),
    TOP_TYPE VARCHAR2(50),
    BOTTOM_TYPE VARCHAR2(50),
    TOP_COLOR VARCHAR2(50),
    BOTTOM_COLOR VARCHAR2(50),
    SHOE_COLOR VARCHAR2(50),
    BACKGROUND_THEME VARCHAR2(50),
    TAGS VARCHAR2(500),
    VIEW_COUNT NUMBER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_OOTD_USER FOREIGN KEY (USER_ID) REFERENCES MEMBERS(ID) ON DELETE CASCADE
);

-- OOTD_LIKES 테이블 (좋아요)
CREATE TABLE OOTD_LIKES (
    OOTD_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (OOTD_ID, USER_ID),
    CONSTRAINT FK_OOTD_LIKE_POST FOREIGN KEY (OOTD_ID) REFERENCES OOTD_POSTS(OOTD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OOTD_LIKE_USER FOREIGN KEY (USER_ID) REFERENCES MEMBERS(ID) ON DELETE CASCADE
);

-- OOTD_COMMENTS 테이블 (댓글)
CREATE TABLE OOTD_COMMENTS (
    COMMENT_ID NUMBER PRIMARY KEY,
    OOTD_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_OOTD_COMMENT_POST FOREIGN KEY (OOTD_ID) REFERENCES OOTD_POSTS(OOTD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OOTD_COMMENT_USER FOREIGN KEY (USER_ID) REFERENCES MEMBERS(ID) ON DELETE CASCADE
);

-- 인덱스 생성
CREATE INDEX IDX_OOTD_USER_ID ON OOTD_POSTS(USER_ID);
CREATE INDEX IDX_OOTD_CREATED_AT ON OOTD_POSTS(CREATED_AT DESC);
CREATE INDEX IDX_OOTD_LIKES_OOTD_ID ON OOTD_LIKES(OOTD_ID);
CREATE INDEX IDX_OOTD_COMMENTS_OOTD_ID ON OOTD_COMMENTS(OOTD_ID);

COMMIT;


------------------------------------------------------
-- 전체 스키마 생성 끝
------------------------------------------------------
